version: '3'

volumes:
  certs-volume:
    external: true
  conf-volume:
    external: true
  webroot-volume:
    external: true

services:
  nginx_proxy:
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - certs-volume:/etc/nginx/certs:ro
      - conf-volume:/etc/nginx/conf.d:ro
      - webroot-volume:/usr/share/nginx/html:ro

  hoster:
    build: .
    container_name: hoster
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs-volume:/etc/nginx/certs
      - conf-volume:/etc/nginx/conf.d
      - webroot-volume:/usr/share/nginx/html

  example1:
    image: nginx
    environment:
      NG_PR_DOMAIN: ${NG_PR_DOMAIN}
      NG_PR_MAINDOMAIN: ${NG_PR_MAINDOMAIN}
      NG_PR_PORT: 80
      NG_PR_EMAIL: ${NG_PR_EMAIL}
    volumes:
      - ./example_html:/usr/share/nginx/html

  # certbot-server:
  #   image: pieterscheffers/certbot-server:latest
  #   volumes:
  #     - ./data/certbot/var_lib_letsencrypt:/var/lib/letsencrypt
  #     - ./data/certbot/etc_letsencrypt:/etc/letsencrypt
