version: '3'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - certs-volume:/etc/nginx/certs:ro
      - conf-volume:/etc/nginx/conf.d:ro

  hoster:
    build: .
    container_name: hoster
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs-volume:/etc/nginx/certs
      - conf-volume:/etc/nginx/conf.d

  example1:
    image: nginx
    environment:
      NG_PR_DOMAIN: www.example.com,example.com
      NG_PR_PORT: 80,
      NG_PR_EMAIL: info@pieterscheffers.nl

  # certbot-server:
  #   image: pieterscheffers/certbot-server:latest
  #   volumes:
  #     - ./data/certbot/var_lib_letsencrypt:/var/lib/letsencrypt
  #     - ./data/certbot/etc_letsencrypt:/etc/letsencrypt

volumes:
  certs-volume:
  conf-volume: