version: '3'

volumes:
  certs-volume:
    external: true
  conf-volume:
    external: true
  webroot-volume:
    external: true

networks:
  main-network:
    external: true

services:
  nginx_proxy:
    restart: always
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - certs-volume:/etc/nginx/certs:ro
      - conf-volume:/etc/nginx/conf.d:ro
      - webroot-volume:/usr/share/nginx/html:ro
    networks:
      - default
      - main-network

  hoster:
    restart: always
    image: pieterscheffers/nginx-hoster
    container_name: hoster
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - certs-volume:/etc/nginx/certs
      - conf-volume:/etc/nginx/conf.d
      - webroot-volume:/usr/share/nginx/html
